api/urls.py
from django.conf.urls import url, include
from rest_framework import routers
from rest_framework_swagger.views import get_swagger_view
from .views import ProductViewSet


app_name = 'api'

router = routers.DefaultRouter()
router.register(r'products', ProductViewSet)

urlpatterns = [
    url(r'^docs/',  get_swagger_view()),
]
urlpatterns += router.urls

eshop/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from . import views

app_name = 'eshop'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^products/', include('products.urls')),
    url(r'^api/', include('api.urls')),
]

products/urls.py
from django.conf.urls import url

from . import views

app_name = 'products'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^list/$', views.list, name='list'),
    url(r'^create/$', views.create, name='create'),
    # use pk as request parameter in favor of generic  views
    url(r'^read/(?P<pk>[0-9]+)/$', views.read, name='read'),
    # url(r'^read/(?P<pk>[0-9]+)/$', views.read.as_view(), name='read'), # generic view
    url(r'^update/(?P<pk>[0-9]+)/$', views.update, name='update'),
    url(r'^update/$', views.update, name='update'),
    url(r'^delete/(?P<pk>[0-9]+)/$', views.delete, name='delete'),
    url(r'^delete/$', views.delete, name='delete'),
]

api/models.py
from django.db import models

# Create your models here.

products/models.py
from django.db import models
from django.utils import timezone

class Product(models.Model):
    name = models.CharField(max_length=30, unique=True)
    price = models.FloatField(default=1.0)
    created_date = models.DateTimeField(
            default=timezone.now)

    def __str__(self):
        return '{}, price is $AUD {:.2f}'.format(self.name, self.price)

products/forms.py
from django.forms import ModelForm
from .models import Product

class ProductForm(ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'price'] # no need to put id
        # exclude = ['created_date']

api/views.py
from rest_framework import viewsets
from products.models import Product
from .serializers import ProductSerializer

class ProductViewSet(viewsets.ModelViewSet):
    queryset = Product.objects.all()
    serializer_class = ProductSerializer

eshop/views.py
import os
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect

# Controller
# Django views.py is the Controller in MVC pattern

def index(request):
    context = {
        'eshop_env': os.environ.get("ESHOP_ENV", None),
    }
    return render(request, 'eshop/index.html', context)

products/views.py
import os
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.views import generic
from django.urls import reverse
from .models import Product
from .forms import ProductForm

# Controller
# Django views.py is the Controller in MVC pattern

def index(request):
    return HttpResponseRedirect(reverse('products:list'))

def list(request):
    latest_production_list = Product.objects.order_by('-created_date')[:50]
    context = {
        'latest_production_list': latest_production_list,
    }
    return render(request, 'product/list.html', context)

def create(request):
    if request.method == 'GET':
        form = ProductForm()
    else:
        # A POST request: Handle Form Upload
        # Bind data from request.POST into a Form
        form = ProductForm(request.POST)
        # If data is valid, proceeds to create a new record and redirect the user
        if form.is_valid():
            product = form.save()
            return HttpResponseRedirect(reverse('products:read', kwargs={'pk': product.id}))

    context = {
        'form': form,
    }
    return render(request, 'product/create.html', context)


# This is the usage of normal controller action
# This way is more flexible than generic view for complex situations
def read(request, pk):
    product = get_object_or_404(Product, pk=pk)
    context = {
            'product': product,
    }
    return render(request, 'product/read.html', context)

# # This is the usage of generic
# class read(generic.DetailView):
#     model = Product
#     template_name = 'product/read.html'

def update(request, pk):
    product = get_object_or_404(Product, pk=pk)
    if request.method == 'GET':
        form = ProductForm(instance=product)
    else:
        # A POST request: Handle Form submit
        # Create Form from instance in db, then merge post request data to update
        form = ProductForm(request.POST, instance=product)
        # If data is valid, proceeds to create a new record and redirect the user
        if form.is_valid():
            product = form.save()
            return HttpResponseRedirect(reverse('products:read', kwargs={'pk': product.id}))

    context = {
        'form': form,
        'product': product,
    }
    return render(request, 'product/update.html', context)

def delete(request, pk):
    product = get_object_or_404(Product, pk=pk)
    product.delete()
    return HttpResponseRedirect(reverse('products:list'))

eshop/templates/eshop/footer.html
<footer class="footer">

	<div class="row footer-top">
			<div class="col-md-12 footer-row">
			</div>

			<div class="col-md-12 footer-row">
				<span class="footer-row-title">联系方式：</span> <span>客服电话：</span><span>电子邮箱：</span><span> 公司地址：
					</span>
			</div>

			<div class="col-md-12 footer-row">
			</div>
	</div>

	<div class="row footer-bottom">
			<div class="col-md-12">
				&#169;&#160;  {% now "Y" %}
				&#160;Sydney Summit Technology Development PTY. LTD
			</div>
	</div>

</footer>

eshop/templates/eshop/header.html
	<!-- Navigation -->
	<nav class="dui-header navbar navbar-inverse navbar-fixed-top"
		role="navigation">
		<div class="">
			<!-- Brand and toggle get grouped for better mobile display -->
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse"
					data-target="#bs-example-navbar-collapse-1">
					<span class="sr-only">Toggle navigation</span>
				</button>
        <a class="navbar-brand"
					href="/">eshop</a>
			</div>

			<!-- Collect the nav links, forms, and other content for toggling -->
			<div class="collapse navbar-collapse"
				id="bs-example-navbar-collapse-1">

				<ul class="nav navbar-nav navbar-left">

						<li><a href="{% url 'products:list' %}">List Product</a></li>
						<li><a href="{% url 'products:create' %}">Create Product</a></li>


				</ul>
			</div>
			<!-- /.navbar-collapse -->
		</div>
		<!-- /.container -->
	</nav>

eshop/templates/eshop/index.html
{% extends 'eshop/layout.html' %}

{% block content %}
    <div class="page-header">
        <h1>Welcome to EShop. This is the {{ eshop_env }} site.</h1>
    </div>
{% endblock %}

eshop/templates/eshop/layout.html
{% load staticfiles %}
<html>
    <head>
        <title>python eshop</title>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="{% static 'css/eshop.css' %}">


        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.js"></script>
    </head>

    <body>

        {% include "./header.html" %}

      	<div class="body">
      		<div class="row">
            {% block content %}
            {% endblock %}
      		</div>
      	</div>

        {% include "./footer.html" %}

    </body>
</html>

products/templates/product/_product.html
<form method="post" action="{{action}}">
  {% csrf_token %}
  <table>
    {{form}}
  </table>
  <input type="submit" value="Submit Form"/>
</form>

products/templates/product/create.html
{% extends 'eshop/layout.html' %}

{% block content %}
  {% url 'products:create' as actionUrl %}
  {% include "./_product.html" with action=actionUrl %}
{% endblock %}

products/templates/product/index.html
{% extends 'eshop/layout.html' %}

{% block content %}
  Index Page
{% endblock %}

products/templates/product/list.html
{% extends 'eshop/layout.html' %}

{% block content %}
    {% if latest_production_list %}
        <script>
          $(document).ready(function() {

            $('a.deleteLink').click(function() {
              swal({
                title : 'Confirm',
                text : "Are you sue to delete?",
                type : 'warning',
                showCancelButton : true,
                confirmButtonColor : '#3085d6',
                cancelButtonColor : '#d33',
                confirmButtonText : 'Yes',
                cancelButtonText : 'Cancel'
              }, function() {
                  alert('hi');
              });
            });

          });

      		function deleteProduct(productId){

      			var action = "{% url 'products:delete' %}" + productId + "/";

      			var form = $("#deleteProductForm");

      			form.attr("action", action);
      			form.submit();
      		}
       </script>


    	<form method="post" id="deleteProductForm">
        {% csrf_token %}
    	</form>

        {% for product in latest_production_list %}

          <div class="col-lg-4">
            <div class="product">
              <div class="top">
                <a href="{% url 'products:read' product.id %}">{{ product.name }}</a>
                <div>
                  <p>$AUD {{ product.price }}</p>
                </div>
              </div>
              <div class="bottom">
                  <a href="{% url 'products:update' product.id %}">update</a>
                  <!--<a id="#deleteLink" href="{% url 'products:delete' product.id %}">delete</a>-->
                  <input class="btn btn-danger center-block pull-right "
															type="button" data-toggle="modal"
															data-target="#confirm-delete_{{product.id}}" value="Delete Product" />


  								<div class="modal fade" id="confirm-delete_{{product.id}}"
  									tabindex="-1" role="dialog"
  									aria-labelledby="myModalLabel" aria-hidden="true">
  									<div class="modal-dialog">
  										<div class="modal-content">
  											<div class="modal-header">
  												<b style="color: red">Confirm</b>
  											</div>
  											<div class="modal-body">Are you sure to delete the product?</div>
  											<div class="modal-footer">
  												<button type="button" class="btn btn-default"
  													data-dismiss="modal">Cancel</button>
  												<a class="btn btn-danger btn-ok"
  													onclick="deleteProduct('{{product.id}}')">Yes</a>
  											</div>
  										</div>
  									</div>
  								</div>
              </div>
            </div>
          </div>
      {% endfor %}
  {% else %}
      <p>No products are available.</p>
  {% endif %}
{% endblock %}

products/templates/product/read.html
{% extends 'eshop/layout.html' %}

{% block content %}
    <ul>
        <li>{{ product.id }}</li>
        <li>{{ product.name }}</li>
        <li>{{ product.price }}</li>
        <li>{{ product.created_date }}</li>
    </ul>
{% endblock %}

products/templates/product/update.html
{% extends 'eshop/layout.html' %}

{% block content %}
    {% url 'products:update' product.id as actionUrl %}
    {% include "./_product.html" with action=actionUrl %}
{% endblock %}